name: on-check-run
run-name: "check-run: ${{ github.event.workflow.name }} (${{ github.event.workflow_run.id }}, ${{ github.event.action }}, ${{ github.event.workflow_run.conclusion }})"
on:
  check_run:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: "echo '${{ toJSON(github.event) }}' | jq"